### ISSUE TITLE
Reading Input

### ISSUE THREAD

**Issue by charl26** [charl26/Abstract-VM#2]
Must be able to read from any file descriptor line by line until exit or ;;

**Comment by charl26** [comment]
Reading the will be done line by line after a line is read in will be sent to validation for syntax then to execution

**Comment by ScheepersDev23** [comment]
If you run your code and enter "push", Enter, "pull", Enter, ";;", <Enter>, the program does not exit, only on the next double semicolon you enter does it exit. It's a bug, not sure why. I'll mark it as a bug

**Comment by ScheepersDev23** [comment]
Resolved.
