### ISSUE TITLE
Validating input

### ISSUE THREAD

**Issue by charl26** [charl26/Abstract-VM#3]
Validation of input must check for

**Comment by charl26** [comment]
• The assembly program includes one or several lexical errors or syntactic errors.
• An instruction is unknown
• Overflow on a value or the result of an operation
• Underflow on a value or the result of an operation
• Instruction pop on an empty stack
• Division/modulo by 0
• The program doesn’t have an exit instruction
• An assert instruction is not true
• The stack is composed of strictly less that two values when an arithmetic instruction
is executed.

**Comment by ScheepersDev23** [comment]
Dependent on Reading Input task because I need to know how the input will be passed to Input Validation method.

**Comment by ScheepersDev23** [comment]
Resolved.

**Comment by ScheepersDev23** [comment]
Input validation does not account for ";;" as end of input.

**Comment by ScheepersDev23** [comment]
Resolved.
